application_name: Relay Mirror Adapter
application_type: Package
description: This package enables the Mirror Networking library to interoperate with
  the Unity Transport package and Relay.
development_stage: Beta
internally_developed: true
language: C#
organization: 6153486bee4c740772d3b017
poc: gladys.kwok@unity3d.com
risk_assessment:
  authentication: No Authentication
  hosting: N/A
  internet_facing: false
  payment_info: false
  pci: false
  personal_info: false
  revenue_impact: false
slack_channel: '#wolfjaw-unity-metaverse'
urls: []
