export MULTIPLAY_ACCESS_KEY_ID=<your-multiplay-access-key-id>
export MULTIPLAY_SECRET_ACCESS_KEY=<your-multiplay-secret-access-key>
export BASIC_AUTH_STRING=$(echo -n $MULTIPLAY_ACCESS_KEY_ID:$MULTIPLAY_SECRET_ACCESS_KEY | base64 | tr -d '\n\r')
export ACCOUNT_SERVICE_ID=<your-multiplay-account-service-id>
export BUILD_MACHINE_ID=<your-multiplay-build-machine-id>
export IMAGE_A_ID=<your-multiplay-image-a-id>
export IMAGE_B_ID=<your-multiplay-image-b-id>
export FLEET_ID=<your-fleet-id>
export PROFILE_ID=<your-profile-id>
export REGION_ID=<your-region-id>